services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    networks:
      - node-network
    depends_on:
      - app

  app:
    build: 
      context: .
    container_name: app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    networks:
      - node-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  node-network:
    driver: bridge